### ISSUE TITLE
Dark Arts -> Addendum: Black

### ISSUE THREAD

**Issue by salrizzo** [EasyFarm/EasyFarm#151]
First off, awesome project - thank you for the time you put into this and the fact that you share it for free.

I've gotten pretty solid with the logic in configuring buffs but can't seem to figure out how to get SCH to stay in Addendum: Black. I can ja Dark Arts using the "if missing" but if i use the same logic for Addendum they will just try to loop since they are two different buffs. Also, trying a recast time of just over 2 hours and 2 hours plus 5 seconds (for DA and A:B, respectively) doesnt seem to play nice, even with setting the recast to ~7200 and once per battle, it doesn't seem to wanna stop trying to cast either. 

Not game breaking by any means, but if you know how to get around this it would be super helpful not just in this case but with other jobs.

Thanks!

**Comment by Mykezero** [comment]
Sorry for the long delay, but I took me some time to realize that the status effect text field actually accepts an regular expression, and that the text: 
```
Dark Arts|Addendum Black
```
will trigger when the character has either Dark Arts or Addendum Black as a status effect. 

Try these setting and see if they work for you: 

For Dark Arts, set it so that it will trigger only when Dark Arts or Addendum Black status effect is missing

![image](https://cloud.githubusercontent.com/assets/5349608/11919824/b557f7f6-a72a-11e5-8d3a-5d5f23424f93.png)

And for Addendum: Black, set so that it will trigger only when Addendum Black status effect is missing. 

![image](https://cloud.githubusercontent.com/assets/5349608/11919832/e861c79e-a72a-11e5-874c-722254209b78.png)

This will give the you behavior of always casting Dark Arts when its missing but not when Addendum: Black is currently applied, and casting Addendum: Black only when it is missing from the player. I haven't tested it in the game but a quick, dirty test does indicate it's possible.
