### ISSUE TITLE
1.0.56 Moving to Target Issue

### ISSUE THREAD

**Issue by SG1234567** [EasyFarm/EasyFarm#153]
Targeting is no longer an issue with EliteMMO. It will locate and attack the next target successfully.
I have found that when the bot needs to move forward towards an enemy (that is currently out of range) it will instead open up the chat and type 'W'.

Thanks for all the help with the issues.

**Comment by Reiver2285** [comment]
EF 1.0.56 works fine so far when you set your Keyborad ingame to Compact1 since this setzup uses WASD to move instead of numpad. 
But EF stops completely after a rondom amount of mobs. even stops to move if you have set a route.

**Comment by Mykezero** [comment]
@Reiver2285 Thanks for the update: I'll see what I can do about tuning the navigation so that it does not require a keyboard setup change. 

This might have something to do with with having no IsRendered function: the program will detect invisible mobs (bats, skeletons, ...) and try to attack them even though they're not spawned (I'll be working on implementing IsRendered next ^^;). 

Does pausing the program and pressing start in a different area of the same zone work? If so, it probably was an invisible mob. Thanks for the all updates: they are really helpful!

**Comment by Reiver2285** [comment]
Pausing and restarting does indeed cause it to fight new targets, but often only a single one.
Its strange why it does that cause where i used EF wont spawn any Time related Mobs like Bats, Skeletons,... Could target a dead Mob maybe

**Comment by Mykezero** [comment]
Alright, navigation should now use the number pad keys for navigation so that no change to keyboard settings are necessary.

**Comment by SG1234567** [comment]
Thank you for this!

**Comment by Mykezero** [comment]
Finally we're making some progress cutting down some of these bugs xD

**Comment by Mykezero** [comment]
@Reiver2285 I've added the bug report for IsRendered #154 being broken since I think that's what's causing the not-moving problem so I'll close this issue down. 

If you want, you can open another issue or use issue #154 to discuss this problem further. I did noticed that after moving to a different area that the program still wanted to go back to the previous location where it got stuck so it's definitely a problem.
