### ISSUE TITLE
The program is crashing after selecting the Character

### ISSUE THREAD

**Issue by C4ndura** [EasyFarm/EasyFarm#171]
I've downloaded the latest release, and made sure I've got installed all necessary additional software (.Net Framewort, Visual C++ Redistributable 64 and x86 bit) but when ever I select my character the program stops working with the following error.

"An exception has occured.

Object reference not set to an object instance."

In addition, the latest release also shows the IDs of non FFXI applications.

**Comment by Mykezero** [comment]
This version of EF use a new API which requires dependencies that were not needed in the previous versions. Please run the dependencies checker if you haven't done so already.  
* http://www.elitemmonetwork.com/forums/viewtopic.php?f=28&t=329.  

In addition, make sure that you running the program as an administrator so that it may access the dll files that are packaged with it. 

The process ids for other applications are only suppose to be shown when no game instance is running. This is to allow easier usage on private servers and for testing (since pol.exe may not be named pol.exe for private server users). Was the game running when you hit Select Character? If so, then this is probably a bug.

**Comment by C4ndura** [comment]
The tool you mentioned showed that there was MSVC++ 2015 missing.

Now I can select the character, but it will still show the process-id’s of other applications i.e. firefox.

But that’s a minor issue.
