### ISSUE TITLE
.100 issue

### ISSUE THREAD

**Issue by Mercurian** [EasyFarm/EasyFarm#241]
I grabbed .100 to see how well it works, since ive been using .98

It spazzes out when you use a stand alone return point now, all the older versions never did that. They would kill and return to zero.

Now you're forced to make a patrol path, kinda don't like that.

**Comment by Mercurian** [comment]
Also, this isn't specific to .100 but something I'd like to see addressed:

No matter what I try to set my detect/wander too, once a day, a mob will spawn right on the border, and i'll chase it, kill it, then the program will stand there because it is beyond wander range.

I'd LOVE for that to stop happening.

**Comment by Mykezero** [comment]
Sorry for the trouble! I had actually forgotten about that functionality, and I must have broken it when updating the pathing code. I'll try to get that fixed today!

If I remember correctly, the intent for stopping the character from pathing outside of the wander distance was actually to prevent the case where someone starts the bot really far away from their route. That way, their character wouldn't attempt to travel half way across the map to their route. 

I'll see what I can do about that: It may be possible to perform that check directly after the user clicks start, and not check it after the bot has started.

**Comment by Mercurian** [comment]
LOL I did that a few times... start the bot for the wrong zone and watch it run straight into a wall! Its cool that you fixed that part, but that it suffered the "stalling" effect as a part of it.

It can't be easy trying to make everything work great, appreciate the effort.

**Comment by Mykezero** [comment]
I've pushed out a new version that fixes that problem where the character spazzes out when using only one waypoint. I'll work on fixing that problem with stalling when the character exceeds the wander distance next.

**Comment by Mercurian** [comment]
So I grabbed 101, so far it's great. I'll post back in here if I find something messed up. Appreciate the effort.

Another suggestion I'd really like to see, is when/how buffs get used, always been kind of a crapshoot, but maybe I do something wrong.

Hasso, for example, if you turn on hasso, the bot refreshes hasso every minute, kinda not needed. If you manually set it to use hasso every 5 minutes, if during that window the bot is voking, or zerking or anything, it negates the hasso, and goes hassoless for 5 whole minutes.

RDM buffs are a big culprit for this too, if I want to haste myself, it'll spam it, if it set it once per battle, its still too much, if i set it for a 9 minute timer, and end up busy during that timer, no haste for 9 minutes, or i get slowed/dispelled again no haste for 9 minutes. Is there a way to make it so if not hasted cast haste etc? if hasso not active use hasso.

(these aren't problems, just suggestions for enhancement and are not a priority)

**Comment by Mykezero** [comment]
There might be a few things I could do to make the recast feature more reliable. One approach would be check if the action has a recast time after cast: if not, then the action probably failed to cast. In this case, I let it attempt it again. 

For now, with spells like haste, you might have better luck setting the On Status field for the actions. 

The status field actually takes a regular expression. You can use this to make it cast haste only when slow and haste are not already applied (the bar '|' character in the middle makes it check for either haste or slow)

![image](https://cloud.githubusercontent.com/assets/5349608/24130262/e7d08f68-0dbd-11e7-93ed-c04bb3e6ecac.png)

For hasso not active, you can use do something similar: 

![image](https://cloud.githubusercontent.com/assets/5349608/24130323/328811de-0dbe-11e7-8779-307494750271.png)

That should force them to be used only when those status effects are not applied. 

I really appreciate the suggestions since this is a lot of stuff that I haven't thought about before ^^

**Comment by Mercurian** [comment]
Ok, so haste 2 works fine, temper works fine (multi strikes)

But, it doesn't want to work with rolls:

I have it set to use corsair's roll, if no corsair's roll, use corsair's roll, but it keeps trying to spam it

**Comment by Mykezero** [comment]
I'll be pushing out an update that will prevent the player from stalling after hitting the wander distance.

Very strange about the haste|slow problem, and that type of set up seems to be working. 

I've configured baraero so that it will only be cast when neither shell, protect nor baraero are active on the player.

![image](https://cloud.githubusercontent.com/assets/5349608/24333524/5373c420-1227-11e7-8bd3-1109dab6bfdf.png)

I'll work on making recast and max use fields more reliable next.

**Comment by Mercurian** [comment]
Yeah I'm not sure why but, 

Caste Haste 2 if no Haste works, Caste Haste 2 if no slow|haste while slowed it would spam trying to overwrite the slow. That's what was happening. 

Also, Cor rolls spam too, 
![kli](https://cloud.githubusercontent.com/assets/4117641/24336453/b21eb882-125d-11e7-84c6-a71e9d3c5911.png)

**Comment by Altalus** [comment]
Quick question, I can see that the “On Status” checkbox is not selected… so this means it’s a yes/no and not an activate/deactivated ?

 

________________________

Guillaume Gingras

**Comment by Mykezero** [comment]
@Mercurian  Looking at the code, you might need to use this for Corsair's Roll: Corsairs Roll
It might not properly handle the single quote. 

The project is using the old FFACETools status effect definitions, which does not contain the single quote. 
https://github.com/EasyFarm/EasyFarm/blob/master/MemoryAPI/Enums/enums.cs#L344

Maybe we should add an autocomplete for that text box so that we know which values are valid?

In addition, I should probably allow other status effects to be trackable even if they aren't specifically in the application. The existing definitions are carry-overs from when the system was using FFACE, but it now uses the EliteAPI so it might be good to revisit this. 

I'll probably need to test the slow|haste problem directly, instead of using baraero ^^;

@Altalus I know this isn't probably the best way, but you can hover over that On Status checkbox and you'll see a tooltip about how to use it: 

![image](https://cloud.githubusercontent.com/assets/5349608/24362706/94f06ad4-12db-11e7-821b-acb72616f2a3.png)

If it's checked, it will trigger the action when the status effect is active (for removing things like poison from the player). 

If unchecked,  it will trigger the action when the status effect is not active (for buffing moves like haste, and protect)

Does this help Altalus?

**Comment by Mercurian** [comment]
Corsairs Roll indeed is what works properly (no apostrophe) Thanks for clearing that up
