### ISSUE TITLE
StateMachine and other misc questions`

### ISSUE THREAD

**Issue by JoshuaTyree** [EasyFarm/EasyFarm#251]
I'm implementing trust support into the application in a fork. 
Work done so far: https://github.com/JoshuaTyree/EasyFarm/commit/be01e9312e7aac68b55aeccdb7af260255ff1fec

I had a few questions about how everything interacts to avoid longer than necessary debugging processes.

1. I added a state with priority of 0. I would expect the state machine to flow like this:  SummonTrustsState > ApproachState > Healing/WeaponSkill/Rest. Sometimes it skips checking if it needs to resummon trusts between mobs, what am I missing?

2. Trusts don't have Jobs in the EliteAPI, it's only byte 0. Any ideas on evaluating if a trust is a healer/mage/paladin job? My current working idea is literally just a dictionary of <string, Job> manually populated with current trusts. Another idea I had was adding a checkbox to the BattleAbility to store whether MP is important or not.

3. In the future we'll need to check if the trust magic spell is on cooldown.  What's the best way to approach that? Just add a cooldown to the BattleAbility?

4. When I attempt to save with the new BattleLists (Including trusts), the profile serializer throws an exception and crashes.  Anything special I have to do to properly serialize the new addition?

EDIT: The Actions collection in the BattleList class appears to be the culprit. When serializing the "Start" battlelist, there's an action that has a null name, etc.  Looks like a blank class.

**Comment by Mykezero** [comment]
1. I would suggest moving the priorities around so that it triggers before the Follow and Start states, but after the SetTarget and SetFighting states. The states are sorted by priority in descending order, so with a priority of 0, it would have executed last.
```
AddState(new DeadState(fface) { Priority = 7 });
AddState(new ZoneState(fface) { Priority = 7 });
AddState(new SetTargetState(fface) { Priority = 7 });
AddState(new SetFightingState(fface) { Priority = 7 });
AddState(new FollowState(fface) { Priority = 5 });
AddState(new RestState(fface) { Priority = 2 });
AddState(new SummonTrustsState(fface) { Priority = 6 });
AddState(new ApproachState(fface) { Priority = 0 });
AddState(new BattleState(fface) { Priority = 3 });
AddState(new WeaponskillState(fface) { Priority = 2 });
AddState(new PullState(fface) { Priority = 4 });
AddState(new StartState(fface) { Priority = 5 });
AddState(new TravelState(fface) { Priority = 1 });
AddState(new HealingState(fface) { Priority = 2 });
AddState(new EndState(fface) { Priority = 3 });
AddState(new StartEngineState(fface) { Priority = Constants.MaxPriority });
```

2. These settings are for determining whether the we should rest when the trusts are injured? If the EliteAPI doesn't say what job these NPCs are, we could add sliders to BattleAbility for HPP and MPP and let the user decide when the trusts should rest. 

3. The program handles a lot of the spell casting checks automatically. As long as the spell index is correct in Windower's spells.xml resource file, then the casting checks should work automatically. The only thing we'd need to account for is whether the trust is already summoned, which you've done already! ^^
![image](https://cloud.githubusercontent.com/assets/5349608/25463117/e1fc9d86-2ac1-11e7-84be-99def849da9f.png)

4. That's a new bug from the last update that I need to patch.

**Comment by JoshuaTyree** [comment]
After a lot of testing, the State's priority seems to operate fine. I think we're on the same page with the rest of the content. I ended up just adding a "Trusts" group box to the AbilityView with HPP and MPP ranges to re-summon the trust.

Related PR: https://github.com/EasyFarm/EasyFarm/pull/252
