### ISSUE TITLE
Unable to Re-summon trusts and engage bug

### ISSUE THREAD

**Issue by Woulia** [EasyFarm/EasyFarm#260]
Hello !

My title says it all and that's the problems I'm having atm. I've just downloaded the latest version and wanted to try the Trust feature but I cannot get it to work. I've a trust re-summon settings on 80 percents MP left (just to give it a shot) but my character is never releasing and re-summoning it.

I am also having another problem. I just chain the same monster over and over again but sometimes my character pulls it (with Fire or whatever I'm setting) and never attacks it. If I don't do it manually whenever I notice it, my character just stand there getting hit and dies.

Is there anything I can do to make it work ?

Edit : seems like I managed to get the trust feature to work by changing the global cooldown settings. Had it around 1000, changed to 4000+. Still running it to see what could be causing the "I don't want to attack anymore" problem.

**Comment by JoshuaTyree** [comment]
The trusts state functions a little differently for everyone because of the way the current state machine operates - it's all timing based. If two mobs are right next to each other, it's possible the system can think it needs to attack the next one instead of check trusts. It's not perfect, but it can definitely be tweaked into working well.

Best solution I had for that was a party manager that prevents the "Leader" from doing anything until the party is in an acceptable state. Don't even have a working version of this - but I was able to get good results with the current implementation on 6 separate characters and systems. Just have to tweak as you found out.

**Comment by Mykezero** [comment]
I've swapped the conditions on some of the states around which might do the trick. Give the new version a try, and let me know if that helps at all! 

There's some other small improvements in that patch as well: 
* Make max trusts configurable (default is 5 in settings)
* Fixed issue where player would not receive updates when its target started moving, resulting in jagged pathing when following a target.

**Comment by Crysez** [comment]
That second bullet point doe...
I think i need a new pair of undies

**Comment by Mykezero** [comment]
Hopefully this did the trick! ^^;
