### ISSUE TITLE
Any guide for modifying this App?

### ISSUE THREAD

**Issue by sonesay** [EasyFarm/EasyFarm#283]
Hi All

Sorry if this is the wrong place to ask but I can't seem to find anywhere else to post it. I just downloaded the source code and would like to start learning how to contribute or make changes to this. Any suggestions about where to begin? Sorry kind of new to Windows .Net as well. I have managed to open up the prooject in Visual Studio 2017 but not sure where to begin.

Thanks

**Comment by Mykezero** [comment]
Hi @sonesay, At one point I did have a development guide for the program, but I seem to have removed it >.<

I'll try to explain what happens when the user hits that start button since it's the most interesting. 

When the start button is pressed, the MasterViewModel class will start the GameEngine. 
[MasterViewModel](https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/ViewModels/MasterViewModel.cs#L161)

The GameEngine will then start the FiniteStateMachine for handling the characters behaviors. 
[GameEngine](https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/States/GameEngine.cs#L65)

The FiniteStateMachine holds a set of States which control the Player's behaviors as the program runs. 
[FiniteStateMachine](https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/States/FiniteStateMachine.cs)

For example, the HealingState will attempt to heal the player when their HPP becomes lower: 
[HealingState](https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/States/HealingState.cs#L60)

The ActionFilter class contains the logic for determining if a spell or job ability is currently usable and the Executor class contains the logic for the moves correctly (they are the heavy lifters in the program). 
* [Action Filters](https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/Classes/ActionFilters.cs)
* [Executor](https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/Classes/Executor.cs)

The Config class acts as the Users way of controlling the behavior of the FiniteStateMachine and its States indirectly: The program will obey changes made to settings and actions which are stored in the Config class. 
https://github.com/EasyFarm/EasyFarm/blob/master/EasyFarm/Classes/Config.cs#L33

Finally, the MemoryAPI class as the interaction point between the Game and the Program. It uses the features of the EliteMMO API created by Wiccaan to interact and send commands to the game. 

Was there anything, in particular, you were interested in doing? 

Hopefully this helps a little bit and sorry for the late response ^^;

**Comment by sonesay** [comment]
Thank you. That is a very good start. It definitely helps a lot.
