### ISSUE TITLE
How detectable is this program?

### ISSUE THREAD

**Issue by Wadabada** [EasyFarm/EasyFarm#338]
How detectable is this program?

**Comment by Mykezero** [comment]
I wouldn't leave it unattended for long periods since it doesn't have player detection and could get stuck on game objects. 

Since the program uses only client side memory operations, it has a low chance of being detected. The program only interacts with the game client and does not speak directly to the server. The program uses only one memory write operation - SetTarget - for quickly setting the player's cursor on enemies, which can also be toggled off in the settings for Tab Based Targeting. 

For a more complete answer, I would definitely ask Atom0s / Wiccaan on the EliteMMO Forums since he's the author who wrote the EliteAPI library this program uses:
http://www.elitemmonetwork.com/forums/

**Comment by Sinnersslayer** [comment]
The only time you can get into a troubles is another player report you.
Unfortunately is is pretty easy to tell who is a bot and who's a real player just from watching it's behaviour.
