### ISSUE TITLE
When im unzip the file my antivirus sign as virust!!!

### ISSUE THREAD

**Issue by RobertoMM1986** [EasyFarm/EasyFarm#507]
Why when im unzip the file i receive virus alarm?

**Comment by Mykezero** [comment]
That could be because of the EliteMMO.dll that is used underneath to power the application. That's written by At0mos, which is a very well trusted member of the FFXI community. He has a forum post about the DLL being false positively flagged by Antivirus sometimes, so I could see this happening: 
* https://www.elitemmonetwork.com/forums/viewtopic.php?f=42&t=281

The remaining code for EasyAsk uses the regular C#/NET features, which is very safe. But yes, I could see that happening.
