### ISSUE TITLE
New update broken enemy detection

### ISSUE THREAD

**Issue by Mercurian** [EasyFarm/EasyFarm#509]
Title

**Comment by Stavorm** [comment]
It seems to be more than that, even If i self target none of the WS Spells or JA work at all.

**Comment by Mercurian** [comment]
That's because you're using the in battle tab. No battle, no actions. Self buffing while not in battle works as always.

Only thing I see not working is ability to track mobs. The same thing they break every time, the same way.

**Comment by Stavorm** [comment]
Oh wow you are right my battle trust and start tabs do not work. Hmm does there just need to be an update to the program?

**Comment by Mercurian** [comment]
Just needs a new API like every other time, hopefully they get one here pretty soon

**Comment by Mercurian** [comment]
Well this is depressing. Usually the API takes minutes not days. For whatever reason it's being prioritized lower than everything else, even though it would've been done quickly.

**Comment by Stavorm** [comment]
hmm, will it be posted ion this thread, usually or will we keep having to check the main page?

**Comment by jazeridan** [comment]
This program and many others only works because of the API. This API is updated by one man that is NOT getting paid for his work. A lot of people are profiting off of his work with no compensation. His website is elitemmo if you want further details. Overall this program and others are in danger of never working again as this is his lowest priority right now. He did say he will update it but he is looking to only offer this API as a paid service. Bottom line though once the the API gets updated on his website then this and other programs requiring it will work again with a simple copy, paste, and overwrite old API.

**Comment by stickynoteme** [comment]
Even then it's only a maybe* on the thread he says he's going to work on rewriting it rather than just patching it up like normal, which could mean old programs like EF that don't have active maintainers who know how to fix things could still be dead in the water if he refactors the API calls in the next version, and no one with the right knowledge cares enough to get it working with it and put up in a public place.

Last status update:
""I am finishing up Ashita's stuff, then going to start working on the rewrite as my next focus.""

**Comment by Mercurian** [comment]
Thank fuck. it's fixed.

**Comment by Stavorm** [comment]
Do you have the link to download the new api? I cant seem to find it.

**Comment by jazeridan** [comment]
Easy farm updates it automatically.

**Comment by Mercurian** [comment]
Well, the newest version does. If you aren't using 132 (I don't) then it doesn't.

https://ext.elitemmonetwork.com/downloads/eliteapi/
